### ISSUE TITLE
Inference Time is Too long

### ISSUE THREAD

**Issue by 553566286** [USTC-JialunPeng/Diverse-Structure-Inpainting#1]
Thanks for your amazing job, the result is amazing. But the inference time is such long.
On 32G V100 the inference time is 34ms. Is it normal？

**Comment by 553566286** [comment]
34s

**Comment by USTC-JialunPeng** [comment]
Yes, it is normal. We have claimed in README.md that our model runs at 45 seconds per image of resolution 256x256 on a single NVIDIA 1080 Ti GPU. It is due to that the autoregressive network will be invoked for 32x32 times in the structure generation.

**Comment by kelisiya** [comment]
> Yes, it is normal. We have claimed in README.md that our model runs at 45 seconds per image of resolution 256x256 on a single NVIDIA 1080 Ti GPU. It is due to that the autoregressive network will be invoked for 32x32 times in the structure generation.

Thank you for your excellent work. How can I solve the reasoning for larger images? Because after 256*256 upsampling, the repaired area will be blurred.

**Comment by USTC-JialunPeng** [comment]
The existing diverse inpainting methods (PIC, UCTGAN, and Ours) can only support fixed resolution because the latent variables of VAE or VQ-VAE must be fixed sizes. If you want to use our method on higher resolution by upsampling, please consider using the [Contextual Residual Aggregation](https://github.com/Ascend-Huawei/Ascend-Canada/tree/master/Models/Research_HiFIll_Model) mechanism to produce higher-frequency residuals.

**Comment by kelisiya** [comment]
Can you share your WeChat?&nbsp;I have some questions about inpainting.

**Comment by kelisiya** [comment]
> The existing diverse inpainting methods (PIC, UCTGAN, and Ours) can only support fixed resolution because the latent variables of VAE or VQ-VAE must be fixed sizes. If you want to use our method on higher resolution by upsampling, please consider using the [Contextual Residual Aggregation](https://github.com/Ascend-Huawei/Ascend-Canada/tree/master/Models/Research_HiFIll_Model) mechanism to produce higher-frequency residuals.

How should fast-pixel-cnn be applied to your project? QAQ

**Comment by USTC-JialunPeng** [comment]
> Can you share your WeChat?&nbsp;I have some questions about inpainting.

You can send me an e-mail and I will share you my WeChat.

**Comment by kelisiya** [comment]
> > Can you share your WeChat? I have some questions about inpainting.
> 
> You can send me an e-mail and I will share you my WeChat.

kelisiyaer@gmail.com , thanks~~

**Comment by asdj32n12dk** [comment]
Hello, is it possible to share "How should fast-pixel-cnn be applied to your project?" here? (I don't have a wechat)

**Comment by USTC-JialunPeng** [comment]
> Hello, is it possible to share "How should fast-pixel-cnn be applied to your project?" here? (I don't have a wechat)

Sorry. We don't apply fast PixelCNN to our project because it's an acceleration technique without changing the results. You can modify our project based on [fast PixelCNN](https://github.com/PrajitR/fast-pixel-cnn) if fast generation is necessary for your usage.

**Comment by asdj32n12dk** [comment]
okay, thank you
