### ISSUE TITLE
Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [512]

### ISSUE THREAD

**Issue by BigbigVegetable** [USTC-JialunPeng/Diverse-Structure-Inpainting#11]
I use a data set with picture sizes of 256*256 and use the pre-trained model you gave for testing. The program reports such an error. Do you know what I did wrong?
Thank you.
![image](https://user-images.githubusercontent.com/39050018/126134792-03707719-4e73-4786-a8e4-e0d2bc3f817b.png)

**Comment by USTC-JialunPeng** [comment]
Hello,

According to "Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint." I wonder if you have modified our code before testing. Maybe your modifications changed the graph.

Best wishes,
Jialun

**Comment by BigbigVegetable** [comment]
Thank you for your reply.
I solved this problem just now. My problem lies in the fact that my image dataset uses absolute paths in the flist file, and my mask dataset uses relative paths. Change the image data set to relative paths, and the program can run successfully.（◠‿◠）
