### ISSUE TITLE
train_vqvae.py and train_texture_generator.py can not accelerated by GPU ?

### ISSUE THREAD

**Issue by wwlCape** [USTC-JialunPeng/Diverse-Structure-Inpainting#14]
Hi, thank you for your great work!
When training the vqvae network, the training time is very long, could you tell me how to accelerate? Thanks for replying!

**Comment by USTC-JialunPeng** [comment]
Training the hierarchical VQ-VAE for 1M iterations takes roughly 8 hours on a single NVIDIA 2080 Ti GPU. If the time is too long for you, you can set a smaller batch size.

**Comment by wwlCape** [comment]
Thank you for quickly replying, I mean that I set "CUDA_VISIBLE_DEVICES=1 python train_vqvae.py" to train vqvae, but it doesn't use GPU. How can I set the GPU.

**Comment by USTC-JialunPeng** [comment]
Maybe there is a problem in your environment that prevents you from using the GPU. Please check if the version of tensorflow is compatible with the version of CUDA.
