### ISSUE TITLE
commit loss is so big

### ISSUE THREAD

**Issue by df720** [USTC-JialunPeng/Diverse-Structure-Inpainting#15]
is this normal?

**Comment by USTC-JialunPeng** [comment]
The commitment loss is about 1e-3~1e-2 in the training of VQ-VAE. How big is your commitment loss?

**Comment by df720** [comment]
About 50-1000.Here is my result in the training, the current step is 20000. I use the environment of tensorflow2.

**Comment by USTC-JialunPeng** [comment]
I didn't train our code on TensorFlow2. I'm sure it's not normal for your commitment loss. The normal one should be above 1e-2 at the beginning of training (100 steps).

**Comment by df720** [comment]
Ok, thanks!
