### ISSUE TITLE
Parameter Settings for random masks

### ISSUE THREAD

**Issue by tanbuzheng** [USTC-JialunPeng/Diverse-Structure-Inpainting#16]
How to set max_delta and margins when using random masks?

**Comment by USTC-JialunPeng** [comment]
Our random models were trained with `max_delta=32` and `margins=0`.

**Comment by tanbuzheng** [comment]
Thanks

**Comment by tanbuzheng** [comment]
During the training, is the number of mask bbox set to 1?
