### ISSUE TITLE
Crop or Resize 

### ISSUE THREAD

**Issue by samuro95** [USTC-JialunPeng/Diverse-Structure-Inpainting#17]
Hi, 
you mention in the README : "For Places2 and ImageNet, we crop a center 256x256." It seems that in your test.py code, you resize all images to 256x256 and don't do any cropping. What did you do for your results in the paper ?

**Comment by USTC-JialunPeng** [comment]
The code corresponds with the testing for CelebA-HQ dataset. We have mentioned "For CelebA-HQ, we resize each image 256x256." For Places2 and ImageNet, we off-line cropped testing images to 256x256 center patches so that the resize operation didn't change anything.
