### ISSUE TITLE
filelist

### ISSUE THREAD

**Issue by xiumin123** [USTC-JialunPeng/Diverse-Structure-Inpainting#18]
I am a newcomer in this field and am very interested in your program. Can you tell me how filelist is generated? Can you publish your code? Thank you.

**Comment by USTC-JialunPeng** [comment]
Thank you for your interest in our work. [Here](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/issues/10) are some examples for generating file lists. I hope it can help you.

**Comment by xiumin123** [comment]
thank you very much
