### ISSUE TITLE
the condition h is NOT used in the train_structure_generator.py

### ISSUE THREAD

**Issue by afad-dataset** [USTC-JialunPeng/Diverse-Structure-Inpainting#3]
How do you train the structure_generator? I see the code in file train_structure_generator.py, where the condition h is totally ignored.

**Comment by USTC-JialunPeng** [comment]
The condition 'h' is injected into each residual gated convolution layer of the autoregressive network. The corresponding code is `with arg_scope([nn.gated_resnet], num_res_filters=nr_res_channel, nonlinearity=resnet_nonlinearity, dropout_p=dropout_p, num_head=nr_head, h=h)` in the '/net/structure_generator.py' (Line 75)

**Comment by afad-dataset** [comment]
> The condition 'h' is injected into each residual gated convolution layer of the autoregressive network. The corresponding code is `with arg_scope([nn.gated_resnet], num_res_filters=nr_res_channel, nonlinearity=resnet_nonlinearity, dropout_p=dropout_p, num_head=nr_head, h=h)` in the '/net/structure_generator.py' (Line 75)

many thanks :-)
