### ISSUE TITLE
Colab Demo? Inference on Custom Images ?

### ISSUE THREAD

**Issue by Adeel-Intizar** [USTC-JialunPeng/Diverse-Structure-Inpainting#5]
Hello, thank you for your amazing implementation
Can you provide a demo file or a colab notebook for custom images, it will be much appreciated and it'll help everyone,

Thank you

**Comment by USTC-JialunPeng** [comment]
Thank you for your suggestion. 
I'm sorry. We have no plans to make a demo for custom images for now.

Best wishes,
Jialun
