### ISSUE TITLE
Why concatenating a matrix of ones? 

### ISSUE THREAD

**Issue by pmorerio** [USTC-JialunPeng/Diverse-Structure-Inpainting#6]
Hi and first of all thanks for the great code!

Can I ask why you stack a matrix of ones in the penultimate channel here?
https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/467b7a9ea3b783c09ec5beb941085bd8e75de2d3/net/structure_generator.py#L30

Wouldn't it make more sense to have `x = tf.concat([x, ones_x*(1-mask), ones_x*mask], 3)` ?
(i.e. you concat the mask as its one-hot encoding).

Best,
P.

**Comment by USTC-JialunPeng** [comment]
It's a good question. 
It originated from the implementation of PixelCNN++, a widely used PixelCNN.
https://github.com/openai/pixel-cnn/blob/bbc15688dd37934a12c2759cf2b34975e15901d9/pixel_cnn_pp/model.py#L36
However, I think it may have little impact on the performance. You can try to remove it and re-train the model.

Best wishes,
Jialun

**Comment by USTC-JialunPeng** [comment]
https://github.com/openai/pixel-cnn/blob/bbc15688dd37934a12c2759cf2b34975e15901d9/pixel_cnn_pp/model.py#L36

**Comment by pmorerio** [comment]
Thanks for your answer!
