### ISSUE TITLE
image processing

### ISSUE THREAD

**Issue by jawadMansoor** [USTC-JialunPeng/Diverse-Structure-Inpainting#9]
Could you please elaborate a little on input image size and size of mask for respective datasets? like celeb input image is 266x266 and the mask is written 256x256, which seems to be wrong.

Specifically, could you share the input image size places 2, and the size of the mask?

In training:
https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/README.md#:~:text=Modify%20data/data_loader.py%20according%20to%20the%20dataset.%20For%20CelebA-HQ%2C%20we%20resize%20each%20image%20to%20266x266%20and%20randomly%20crop%20a%20256x256.%20For%20Places2%20and%20ImageNet%2C%20we%20randomly%20crop%20a%20256x256

In testing
https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/main/README.md#:~:text=Collect%20the%20testing%20set.%20For%20CelebA-HQ%2C%20we%20resize%20each%20image%20to%20256x256.%20For%20Places2%20and%20ImageNet%2C%20we%20crop%20a%20center%20256x256.

I have tested the pre-trained model and found the results to be very off, attaching two sample-generated images.
![00000](https://user-images.githubusercontent.com/39364225/124399422-c9496380-dd34-11eb-9039-10ab5a3d1f9f.png)
![00001](https://user-images.githubusercontent.com/39364225/124399429-d23a3500-dd34-11eb-81fe-3f4ba55aa138.png)

**Comment by USTC-JialunPeng** [comment]
Thanks for your questions.

All image sizes and mask sizes are 256x256. For the training of CelebA-HQ, we resize face images of 1024x1024 to 266x266 and then randomly crop 256x256 patches following [Pluralistic Image Completion](https://github.com/lyndonzheng/Pluralistic-Inpainting/blob/1ca1855615fed8b686ca218c6494f455860f9996/options/base_options.py#L27-L28). It is a simple data augmentation but introduces a small domain gap between training and testing. 

We have mentioned in REAMDE.md that the center_mask models are trained with images of 256x256 resolution with center 128x128 holes. The random_mask models are trained with images of 256x256 resolution with random regular and irregular holes. The random regular and irregular holes are generated by using [net/nn.py](https://github.com/USTC-JialunPeng/Diverse-Structure-Inpainting/blob/467b7a9ea3b783c09ec5beb941085bd8e75de2d3/net/nn.py#L10-L130).

As for your examples, we recommend using our random_mask model trained on Places2. If you are using our center_mask model trained on Places2, the inpainting results may be bad when the center hole is smaller than 128x128.

Best wishes,
Jialun

**Comment by jawadMansoor** [comment]
Thanks, Jialun.

it is working now. Great work!
